# Generated by Django 4.2.6 on 2023-10-16 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authan', '0002_rename_name_user_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='first_name',
            new_name='name',
        ),
    ]
