# Generated by Django 4.2.6 on 2023-10-15 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainee',
            name='bdate',
        ),
    ]
